spring:
  application:
    name: payment_server

  profiles:
    active: dev

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: payment-server
      retry:
        initial-interval: 2000  # 2초 간격
        max-attempts: 30        # 30번 (총 1분)
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/