# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support and
# documentation.

# 각 서비스 워크 플로우
name: Payment CI/CD

# 이 레포에 push/pr이 발생하면 실행 테스트 겸
on:
  push:
    branches: [ "main", "dev", "feature/**" ]
  pull_request:
    branches: [ "main", "dev", "feature/**" ]

jobs:
  call-reusable-deploy:
    # 1. .github 레포의 템플릿 파일을 호출
    # 'YOUR-ORGANIZATION' 부분은 실제 조직 이름으로 변경해야 합니다.후
    uses: nhnacademy-be12-high-five/.github/.github/workflows/shared-workflow.yml@main

    # 2. 템플릿에 필요한 '입력값(inputs)'을 전달
    with:
      service-name: 'payment-server'
      deploy-path: '~/www/nhnbook'

    # 3. 템플릿에 필요한 '시크릿'을 전달
    # 'secrets: inherit'를 쓰면 이 레포의 시크릿을 모두 넘깁니다.
    secrets: inherit