name: Payment Service CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  # PR 검증용 Job (배포 X, 테스트 O)
  ci-check:
    if: github.event_name == 'pull_request'
    uses: nhnacademy-be12-high-five/.github/.github/workflows/service-workflow.yml@main
    with:
      project-key: team5-payment-service
      docker-image: fbxogns123/payment-server
      container-name: payment_server
      # 테스트를 수행해 품질 검사
      maven-args: "-B"
      # 배포 비활성화
      deploy-enabled: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_IP: ${{ secrets.SSH_IP }}
      SSH_ID: ${{ secrets.SSH_ID }}
      SSH_PW: ${{ secrets.SSH_PW }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

  # 실제 배포용 Job (Merge 시 실행)
  cd-deploy:
    if: github.event_name == 'push'
    uses: nhnacademy-be12-high-five/.github/.github/workflows/service-workflow.yml@main
    with:
      project-key: team5-payment-service
      docker-image: fbxogns123/payment-server
      container-name: payment_server
      # 배포 단계에서는 속도를 위해 테스트 스킵 (이미 PR에서 통과했으므로)
      maven-args: "-B -DskipTests"
      # 배포 활성화
      deploy-enabled: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SSH_IP: ${{ secrets.SSH_IP }}
      SSH_ID: ${{ secrets.SSH_ID }}
      SSH_PW: ${{ secrets.SSH_PW }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
